"""Add missing unique constraint for social posts platform ID

Revision ID: bda5beddf408
Revises: eedcd7277705
Create Date: 2025-07-03 22:56:06.872948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda5beddf408'
down_revision: Union[str, Sequence[str], None] = 'eedcd7277705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema.
    
    Apply migration changes to upgrade the database schema.
    This function should contain all forward migration logic.
    
    Safety checks:
    - Always use transactions for schema changes
    - Test migrations on a copy of production data first
    - Ensure all constraints can be satisfied
    - Consider impact on large tables
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_social_posts_platform_id', 'social_posts', ['platform', 'platform_post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema.
    
    Revert migration changes to downgrade the database schema.
    This function should contain all backward migration logic.
    
    Safety checks:
    - Ensure downgrade doesn't cause data loss
    - Test downgrade path thoroughly
    - Consider if data migration is needed
    - Document any irreversible changes
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_social_posts_platform_id', 'social_posts', type_='unique')
    # ### end Alembic commands ###
